import { useCallback, useEffect, useMemo, useState, type CSSProperties, type FormEvent } from 'react'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Boxes, Check, ChevronDown, CircleHelp, Cloud, Command, Database, FileCheck2, Fingerprint, GitBranch, LayoutDashboard, LockKeyhole, LogOut, Menu, Radar, RefreshCw, Search, Shield, ShieldAlert, ShieldCheck, SlidersHorizontal, X } from 'lucide-react'

type Provider = 'aws' | 'gcp' | 'azure'
type Resource = { id: string; provider: Provider; kind: string; name: string; parentId?: string; region?: string; attributes: Record<string, string> }
type Finding = { id: string; ruleId: string; resourceId: string; title: string; severity: string; actual: string; frameworks: string[]; remediation: string }
type Rule = { id: string; provider: Provider; title: string; severity: string; frameworks: string[] }
type Scan = { id: string; provider: Provider; status: string; startedAt: string; message?: string; resources: number; findings: number }
type Graph = { nodes: Resource[]; edges: { source: string; target: string; type: string }[] }
type View = 'overview' | 'findings' | 'inventory' | 'graph' | 'policies' | 'activity'

const nav: { title: string; items: { label: string; view: View; icon: typeof Cloud }[] }[] = [
  { title: 'WORKSPACE', items: [{ label: 'Overview', view: 'overview', icon: LayoutDashboard }, { label: 'Findings', view: 'findings', icon: ShieldAlert }, { label: 'Inventory', view: 'inventory', icon: Boxes }, { label: 'Infrastructure graph', view: 'graph', icon: GitBranch }] },
  { title: 'GOVERNANCE', items: [{ label: 'Security rules', view: 'policies', icon: FileCheck2 }, { label: 'Scan activity', view: 'activity', icon: Activity }] },
]
const names: Record<Provider, string> = { aws: 'Amazon Web Services', gcp: 'Google Cloud', azure: 'Microsoft Azure' }
const shortNames: Record<Provider, string> = { aws: 'AWS', gcp: 'GCP', azure: 'Azure' }

async function request<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/v1/${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, ...(init?.body ? { 'Content-Type': 'application/json' } : {}) }, cache: 'no-store' })
  if (!response.ok) throw new Error(response.status === 401 ? 'Invalid API token. Check your connection and try again.' : `Request failed (${response.status}). ${response.status === 502 ? 'The scan did not complete; check server logs and cloud permissions.' : ''}`)
  return response.json() as Promise<T>
}

function date(value: string) { return new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) }
function compact(value: string) { return value.length > 40 ? `${value.slice(0, 21)}…${value.slice(-12)}` : value }
function ProviderMark({ provider }: { provider: Provider }) { return <span className={`provider-mark provider-${provider}`}>{provider === 'aws' ? 'a' : provider === 'gcp' ? <Cloud size={18} /> : <span className="azure-symbol">◢</span>}</span> }
function Severity({ value }: { value: string }) { return <span className={`severity severity-${value}`}><span className="severity-dot" />{value}</span> }
function Empty({ icon: Icon, title, detail }: { icon: typeof Cloud; title: string; detail: string }) { return <div className="empty"><div className="empty-icon"><Icon size={22} /></div><strong>{title}</strong><p>{detail}</p></div> }

export default function App() {
  const [token, setToken] = useState('')
  const [draft, setDraft] = useState('')
  const [view, setView] = useState<View>('overview')
  const [resources, setResources] = useState<Resource[]>([])
  const [findings, setFindings] = useState<Finding[]>([])
  const [rules, setRules] = useState<Rule[]>([])
  const [scans, setScans] = useState<Scan[]>([])
  const [graph, setGraph] = useState<Graph>({ nodes: [], edges: [] })
  const [busy, setBusy] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const [providerFilter, setProviderFilter] = useState('all')
  const [selectedFinding, setSelectedFinding] = useState<Finding | null>(null)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [scanMenu, setScanMenu] = useState(false)

  const refresh = useCallback(async (secret: string) => {
    setLoading(true)
    try {
      const [nextResources, nextFindings, nextRules, nextScans, nextGraph] = await Promise.all([
        request<Resource[]>('resources?limit=1000', secret), request<Finding[]>('findings?limit=1000', secret), request<Rule[]>('rules', secret), request<Scan[]>('scans', secret), request<Graph>('graph?limit=1000', secret),
      ])
      setResources(nextResources); setFindings(nextFindings); setRules(nextRules); setScans(nextScans); setGraph(nextGraph); setError('')
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to connect to the API.') }
    finally { setLoading(false) }
  }, [])

  useEffect(() => { if (token) void refresh(token) }, [token, refresh])
  const connect = (event: FormEvent) => { event.preventDefault(); if (draft.trim()) { setToken(draft.trim()); setDraft('') } }
  const scan = async (provider: Provider) => {
    setScanMenu(false); setBusy(true); setError('')
    try { await request<Scan>('scans', token, { method: 'POST', body: JSON.stringify({ provider }) }); await refresh(token) }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Scan failed.'); await refresh(token).catch(() => undefined) }
    finally { setBusy(false) }
  }
  const filteredFindings = useMemo(() => findings.filter(item => {
    const resource = resources.find(entry => entry.id === item.resourceId)
    return (providerFilter === 'all' || resource?.provider === providerFilter) && `${item.title} ${item.ruleId} ${resource?.name ?? ''}`.toLowerCase().includes(query.toLowerCase())
  }), [findings, resources, query, providerFilter])
  const filteredResources = useMemo(() => resources.filter(item => (providerFilter === 'all' || item.provider === providerFilter) && `${item.name} ${item.kind} ${item.id}`.toLowerCase().includes(query.toLowerCase())), [resources, query, providerFilter])
  const affected = new Set(findings.map(item => item.resourceId)).size
  const latest = scans[0]
  const select = (next: View) => { setView(next); setQuery(''); setProviderFilter('all'); setMobileOpen(false) }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Shield size={21} strokeWidth={2.4} /></div><span>maestro<span className="brand-period">.</span></span><button className="mobile-close icon-button" aria-label="Close menu" onClick={() => setMobileOpen(false)}><X size={18} /></button></div>
      <div className="workspace-switch"><div className="workspace-icon">M</div><div><strong>My workspace</strong><small>Security operations</small></div><ChevronDown size={15} /></div>
      <nav aria-label="Main navigation">{nav.map(group => <div className="nav-group" key={group.title}><div className="nav-title">{group.title}</div>{group.items.map(item => <button key={item.view} className={`nav-item ${view === item.view ? 'nav-active' : ''}`} onClick={() => select(item.view)}><item.icon size={17} strokeWidth={1.9} /><span>{item.label}</span>{item.view === 'findings' && findings.length > 0 && <span className="nav-count">{findings.length}</span>}</button>)}</div>)}</nav>
      <div className="sidebar-bottom"><div className="security-note"><ShieldCheck size={19} /><div><strong>Human in control</strong><p>Recommendations are never applied automatically.</p></div></div><div className="sidebar-user"><div className="user-avatar">OP</div><div><strong>Operator</strong><small>{token ? 'API connected' : 'Not connected'}</small></div><span className={`status-dot ${token && !error ? 'status-online' : ''}`} /></div></div>
    </aside>
    {mobileOpen && <button className="mobile-overlay" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}
    <div className="main-area">
      <header className="topbar"><div className="breadcrumbs"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><span>Workspace</span><span className="crumb-divider">/</span><strong>{view === 'policies' ? 'Security rules' : view === 'activity' ? 'Scan activity' : view === 'graph' ? 'Infrastructure graph' : view[0].toUpperCase() + view.slice(1)}</strong></div><div className="top-actions"><span className={`connection-indicator ${token && !error ? 'connected' : ''}`}><span />{token && !error ? 'Connected' : 'Disconnected'}</span><button className="icon-button help-button" title="Project documentation" onClick={() => window.open('https://github.com/mohdsaad0786/Maestro-', '_blank', 'noopener,noreferrer')}><CircleHelp size={18} /></button>{token && <button className="icon-button" title="Disconnect" aria-label="Disconnect" onClick={() => { setToken(''); setResources([]); setFindings([]); setScans([]); setRules([]); setGraph({ nodes: [], edges: [] }); setError('') }}><LogOut size={18} /></button>}</div></header>
      <main className="content"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> CLOUD SECURITY POSTURE</div><h1>{view === 'overview' ? 'Security overview' : view === 'findings' ? 'Security findings' : view === 'inventory' ? 'Cloud inventory' : view === 'graph' ? 'Infrastructure graph' : view === 'policies' ? 'Security rules' : 'Scan activity'}</h1><p>{view === 'overview' ? 'One clear view of what matters across your cloud.' : view === 'findings' ? 'Investigate misconfigurations and review recommended fixes.' : view === 'inventory' ? 'Explore the cloud resources discovered in your workspace.' : view === 'graph' ? 'Understand how your cloud resources relate.' : view === 'policies' ? 'The curated controls evaluated in every scan.' : 'See what was scanned, when, and how it went.'}</p></div><div className="heading-actions"><button className="button button-secondary" disabled={!token || loading} onClick={() => void refresh(token)}><RefreshCw size={15} className={loading ? 'spin' : ''} /> Refresh</button><div className="scan-wrap"><button className="button button-primary" disabled={!token || busy} onClick={() => setScanMenu(!scanMenu)}><Radar size={16} /> {busy ? 'Scanning…' : 'New scan'} <ChevronDown size={14} /></button>{scanMenu && <div className="scan-popover"><div className="popover-label">SCAN A PROVIDER</div>{(['aws', 'gcp', 'azure'] as Provider[]).map(provider => <button key={provider} onClick={() => void scan(provider)}><ProviderMark provider={provider} /><span>{names[provider]}</span><ArrowRight size={14} /></button>)}</div>}</div></div></div>
      {error && <div className="alert" role="alert"><ShieldAlert size={18} /><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError('')}><X size={17} /></button></div>}
      {!token && <form className="connect-banner" onSubmit={connect}><div className="connect-icon"><LockKeyhole size={21} /></div><div className="connect-copy"><strong>Connect your workspace</strong><span>Enter your API token to load your security posture. Your token stays in this browser tab only.</span></div><input aria-label="API token" type="password" minLength={32} placeholder="Paste your API token" value={draft} onChange={event => setDraft(event.target.value)} required /><button className="button button-primary" type="submit">Connect <ArrowRight size={15} /></button></form>}
      {view === 'overview' && <>
        <div className="metrics-grid"><Metric icon={Boxes} label="Discovered resources" value={resources.length} foot="Across connected clouds" accent="violet" /><Metric icon={ShieldAlert} label="Open findings" value={findings.length} foot={findings.length ? `${findings.filter(item => item.severity === 'critical').length} critical priority` : 'No findings in snapshot'} accent="coral" /><Metric icon={Fingerprint} label="Affected resources" value={affected} foot="Require human review" accent="amber" /><Metric icon={FileCheck2} label="Active security rules" value={rules.length} foot="Curated, deterministic checks" accent="cyan" /></div>
        <div className="overview-grid"><section className="panel posture-panel"><div className="panel-heading"><div><span className="section-kicker">CLOUD COVERAGE</span><h2>Provider posture</h2></div><span className="subtle-label">CURRENT SNAPSHOT</span></div><div className="provider-list">{(['aws','gcp','azure'] as Provider[]).map(provider => { const items = resources.filter(resource => resource.provider === provider && resource.parentId); const problem = findings.filter(finding => items.some(item => item.id === finding.resourceId)); return <div className="provider-row" key={provider}><ProviderMark provider={provider} /><div className="provider-details"><strong>{names[provider]}</strong><span>{items.length} {items.length === 1 ? 'resource' : 'resources'} discovered</span></div><div className="provider-findings"><strong>{problem.length}</strong><span>findings</span></div><ArrowUpRight className="row-arrow" size={16} /></div> })}</div><div className="panel-footer"><span><span className="tiny-indicator" /> Provider health reflects last successful scans</span></div></section>
        <section className="panel risk-panel"><div className="panel-heading"><div><span className="section-kicker">RISK DISTRIBUTION</span><h2>Findings by severity</h2></div><Shield size={18} className="muted-icon" /></div><div className="risk-body"><div className="risk-ring" style={{ '--critical': `${findings.length ? findings.filter(item => item.severity === 'critical').length / findings.length * 100 : 0}%` } as CSSProperties}><div><strong>{findings.length}</strong><span>TOTAL FINDINGS</span></div></div><div className="risk-legend">{(['critical','high','medium','low'] as const).map(severity => <div key={severity}><span className={`legend-dot legend-${severity}`} /><span>{severity[0].toUpperCase() + severity.slice(1)}</span><strong>{findings.filter(item => item.severity === severity).length}</strong></div>)}</div></div><div className="risk-hint"><ShieldCheck size={16} /> Each finding includes a human-reviewed remediation suggestion.</div></section></div>
        <div className="overview-grid lower-grid"><section className="panel recent-panel"><div className="panel-heading"><div><span className="section-kicker">PRIORITY QUEUE</span><h2>Recent findings</h2></div><button className="text-link" onClick={() => select('findings')}>View all <ArrowRight size={15} /></button></div>{findings.length ? <div className="finding-list">{findings.slice(0, 4).map(item => <FindingRow key={item.id} finding={item} resource={resources.find(resource => resource.id === item.resourceId)} onClick={() => setSelectedFinding(item)} />)}</div> : <Empty icon={ShieldCheck} title="No findings yet" detail="Run a cloud scan to see your posture here." />}</section><section className="panel activity-panel"><div className="panel-heading"><div><span className="section-kicker">LATEST RUN</span><h2>Scan activity</h2></div><button className="text-link" onClick={() => select('activity')}>History <ArrowRight size={15} /></button></div>{latest ? <div className="latest-scan"><div className={`scan-status ${latest.status === 'completed' ? 'scan-success' : 'scan-failed'}`}>{latest.status === 'completed' ? <Check size={18} /> : <X size={18} />}</div><strong>{latest.status === 'completed' ? 'Scan completed' : 'Scan failed'}</strong><span>{names[latest.provider]} · {date(latest.startedAt)}</span><div className="scan-stats"><div><strong>{latest.resources}</strong><span>resources</span></div><div><strong>{latest.findings}</strong><span>findings</span></div></div></div> : <Empty icon={Radar} title="Awaiting your first scan" detail="Choose a cloud provider to get started." />}</section></div>
      </>}
      {(view === 'findings' || view === 'inventory' || view === 'policies') && <section className="panel data-panel"><div className="table-toolbar"><div className="search-box"><Search size={17} /><input aria-label="Search" value={query} onChange={event => setQuery(event.target.value)} placeholder={view === 'findings' ? 'Search findings...' : view === 'inventory' ? 'Search resources...' : 'Search rules...'} /></div><div className="filter-wrap"><SlidersHorizontal size={16} /><select aria-label="Filter provider" value={providerFilter} onChange={event => setProviderFilter(event.target.value)}><option value="all">All providers</option><option value="aws">AWS</option><option value="gcp">GCP</option><option value="azure">Azure</option></select></div></div>
        {view === 'findings' && (filteredFindings.length ? <div className="table-scroll"><table><thead><tr><th>FINDING</th><th>SEVERITY</th><th>PROVIDER</th><th>RESOURCE</th><th>FRAMEWORKS</th><th /></tr></thead><tbody>{filteredFindings.map(item => { const resource = resources.find(entry => entry.id === item.resourceId); return <tr key={item.id} onClick={() => setSelectedFinding(item)} className="clickable-row"><td><strong>{item.title}</strong><small>{item.ruleId}</small></td><td><Severity value={item.severity} /></td><td>{resource && <span className="table-provider"><ProviderMark provider={resource.provider} />{shortNames[resource.provider]}</span>}</td><td className="mono-cell">{resource?.name ?? compact(item.resourceId)}</td><td>{item.frameworks.slice(0, 2).join(', ')}</td><td><ArrowUpRight size={15} /></td></tr> })}</tbody></table></div> : <Empty icon={ShieldCheck} title="No matching findings" detail="Try another filter or run a scan." />)}
        {view === 'inventory' && (filteredResources.length ? <div className="table-scroll"><table><thead><tr><th>RESOURCE</th><th>PROVIDER</th><th>TYPE</th><th>REGION</th><th>FINDINGS</th></tr></thead><tbody>{filteredResources.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{compact(item.id)}</small></td><td><span className="table-provider"><ProviderMark provider={item.provider} />{shortNames[item.provider]}</span></td><td>{item.kind.replaceAll('_', ' ')}</td><td>{item.region || '—'}</td><td><span className="count-pill">{findings.filter(finding => finding.resourceId === item.id).length}</span></td></tr>)}</tbody></table></div> : <Empty icon={Boxes} title="No matching resources" detail="Run a scan to discover resources." />)}
        {view === 'policies' && (rules.filter(rule => (providerFilter === 'all' || rule.provider === providerFilter) && `${rule.title} ${rule.id}`.toLowerCase().includes(query.toLowerCase())).length ? <div className="table-scroll"><table><thead><tr><th>RULE</th><th>PROVIDER</th><th>SEVERITY</th><th>FRAMEWORKS</th></tr></thead><tbody>{rules.filter(rule => (providerFilter === 'all' || rule.provider === providerFilter) && `${rule.title} ${rule.id}`.toLowerCase().includes(query.toLowerCase())).map(rule => <tr key={rule.id}><td><strong>{rule.title}</strong><small>{rule.id}</small></td><td><span className="table-provider"><ProviderMark provider={rule.provider} />{shortNames[rule.provider]}</span></td><td><Severity value={rule.severity} /></td><td>{rule.frameworks.join(', ')}</td></tr>)}</tbody></table></div> : <Empty icon={FileCheck2} title="No matching rules" detail="Try another filter." />)}</section>}
      {view === 'graph' && <section className="panel graph-panel"><div className="panel-heading"><div><span className="section-kicker">RELATIONSHIPS</span><h2>Cloud resource map</h2></div><span className="subtle-label">{graph.edges.length} CONNECTIONS</span></div>{graph.nodes.length ? <div className="graph-groups">{(['aws','gcp','azure'] as Provider[]).map(provider => { const nodes = graph.nodes.filter(node => node.provider === provider); if (!nodes.length) return null; return <div className="graph-group" key={provider}><div className="graph-provider"><ProviderMark provider={provider} /><strong>{names[provider]}</strong><span>{nodes.length} nodes</span></div><div className="graph-tree">{nodes.filter(node => !node.parentId).map(parent => <div className="graph-parent" key={parent.id}><div className="graph-node root-node"><Database size={17} /><span>{parent.name}</span><small>{parent.kind}</small></div><div className="graph-children">{nodes.filter(node => node.parentId === parent.id).map(child => <div className="graph-node child-node" key={child.id}><Boxes size={16} /><span>{child.name}</span><small>{findings.filter(item => item.resourceId === child.id).length} findings</small></div>)}</div></div>)}</div></div> })}</div> : <Empty icon={GitBranch} title="Your graph starts with a scan" detail="Discover resources to reveal cloud relationships." />}</section>}
      {view === 'activity' && <section className="panel data-panel">{scans.length ? <div className="table-scroll"><table><thead><tr><th>PROVIDER</th><th>STATUS</th><th>STARTED</th><th>RESOURCES</th><th>FINDINGS</th><th>SCAN ID</th></tr></thead><tbody>{scans.map(item => <tr key={item.id}><td><span className="table-provider"><ProviderMark provider={item.provider} />{names[item.provider]}</span></td><td><span className={`activity-status ${item.status === 'completed' ? 'activity-ok' : 'activity-error'}`}>{item.status === 'completed' ? <Check size={14} /> : <X size={14} />}{item.status}</span></td><td>{date(item.startedAt)}</td><td>{item.resources}</td><td>{item.findings}</td><td className="mono-cell">{item.id.slice(0, 12)}…</td></tr>)}</tbody></table></div> : <Empty icon={Activity} title="No scans recorded" detail="Start a scan to see the activity timeline." />}</section>}
      <footer className="page-footer"><span>MAESTRO <span className="footer-dot">•</span> Security without the noise</span><span>Read-only discovery <span className="footer-dot">•</span> Human-approved remediation</span></footer></main>
    </div>
    {selectedFinding && <div className="drawer-backdrop" onClick={() => setSelectedFinding(null)}><div className="drawer" role="dialog" aria-modal="true" aria-label="Finding details" onClick={event => event.stopPropagation()}><div className="drawer-head"><span>FINDING DETAILS</span><button className="icon-button" aria-label="Close details" onClick={() => setSelectedFinding(null)}><X size={20} /></button></div><div className="drawer-body"><Severity value={selectedFinding.severity} /><h2>{selectedFinding.title}</h2><p className="drawer-intro">This resource does not match the expected security configuration. Review the recommendation before making any infrastructure changes.</p><div className="detail-block"><span>RESOURCE</span><strong>{resources.find(item => item.id === selectedFinding.resourceId)?.name ?? selectedFinding.resourceId}</strong></div><div className="detail-block"><span>RULE ID</span><strong>{selectedFinding.ruleId}</strong></div><div className="detail-block"><span>OBSERVED VALUE</span><strong>{selectedFinding.actual}</strong></div><div className="detail-block"><span>FRAMEWORK REFERENCES</span><div className="framework-tags">{selectedFinding.frameworks.map(framework => <span key={framework}>{framework}</span>)}</div></div><div className="remediation-box"><div><Command size={17} /><strong>Terraform recommendation</strong></div><pre>{selectedFinding.remediation}</pre><small>Illustrative configuration only. Validate against your IaC and change-control process; Maestro never applies changes.</small></div></div></div></div>}
  </div>
}

function Metric({ icon: Icon, label, value, foot, accent }: { icon: typeof Cloud; label: string; value: number; foot: string; accent: string }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><div className={`metric-icon accent-${accent}`}><Icon size={19} /></div></div><strong>{value.toLocaleString()}</strong><div className="metric-foot"><ArrowDownRight size={14} /> {foot}</div></div> }
function FindingRow({ finding, resource, onClick }: { finding: Finding; resource?: Resource; onClick: () => void }) { return <button className="finding-row" onClick={onClick}><span className={`finding-icon finding-${finding.severity}`}><ShieldAlert size={17} /></span><span className="finding-info"><strong>{finding.title}</strong><small>{resource?.name ?? compact(finding.resourceId)} · {resource?.provider.toUpperCase() ?? 'Cloud'}</small></span><Severity value={finding.severity} /><ArrowUpRight className="row-arrow" size={16} /></button> }
